name: Calculator CI

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: List Project Files
        run: ls -la

      - name: Validation Complete
        run: echo "Calculator Project Validation Successful"